name: Deploy to production

on:
  push:
    branches:
      - production

jobs:
  redeploy_everything:
    name: Deploying everything to the production cluster
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@44.202.179.116 << 'EOF'
            cd book-my-show/ && git pull
            pnpm install
            pnpm run build
            pm2 restart frontend-server
            pm2 restart http-server
            pm2 restart ws-server
          EOF
