name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@3.236.127.2 << 'EOF'
            cd book-my-show
            git pull
            pnpm install
            pnpm run build
            pm2 restart frontend-server
            pm2 restart http-server
            pm2 restart ws-server
          EOF
